### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)
vector.shape, vector

((10,),
 array([0.50863653, 0.55254229, 0.18093487, 0.19696164, 0.24708983,
        0.2980327 , 0.46100944, 0.82054225, 0.68978868, 0.3882674 ]))

In [3]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
matrix.shape, matrix

((3, 3),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector_sum_round = np.round(vector + 10, 2)
vector_sum_round

array([10.51, 10.55, 10.18, 10.2 , 10.25, 10.3 , 10.46, 10.82, 10.69,
       10.39])

In [5]:
vector_multi = vector * 2
vector_multi

array([1.01727307, 1.10508459, 0.36186974, 0.39392329, 0.49417967,
       0.5960654 , 0.92201888, 1.64108451, 1.37957736, 0.77653479])

In [6]:
vector_pow = vector ** 2
vector_pow

array([0.25871112, 0.30530299, 0.03273743, 0.03879389, 0.06105339,
       0.08882349, 0.2125297 , 0.67328959, 0.47580842, 0.15075157])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
result_matrix = np.dot(A.T, B.T)
result_matrix.shape, result_matrix

((2, 2),
 array([[0.7281, 0.2034],
        [0.5202, 0.2846]]))

При множенні матриці розмірністю (2, 2) на вектор розмірністю (2, 1) то в результаті отримаємо вектор розмірністю (2, 1). В заданому випадку цей вектор матиме такі ж значення, які знаходяться в 2 колонці result_matrix

In [9]:
matrix_vector = np.dot(result_matrix, C)
matrix_vector.shape, matrix_vector

((2, 1),
 array([[0.2034],
        [0.2846]]))

При множенні матриці розмірністю (2, 2) на матрицю розмірністю (2, 2) ми так само отримаємо матрицю розмірністю (2, 2). При цьому стовпці матриці result_matrix поміняються місцями (перший стовпець стане другим, а другий - першим)

In [10]:
matrix_matrix = np.dot(result_matrix, D)
matrix_matrix.shape, matrix_matrix

((2, 2),
 array([[0.2034, 0.7281],
        [0.2846, 0.5202]]))


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
result_matrix_transp = result_matrix.T
result_matrix_transp

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [12]:
vector_transp = vector.T
vector_transp.shape, vector_transp

((10,),
 array([0.50863653, 0.55254229, 0.18093487, 0.19696164, 0.24708983,
        0.2980327 , 0.46100944, 0.82054225, 0.68978868, 0.3882674 ]))

Після транспонування жодних змін не відбулось. Це пов'язано з тим, що в даному випадку вектор у нас одновимірний.

In [13]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.50863653],
       [0.55254229],
       [0.18093487],
       [0.19696164],
       [0.24708983],
       [0.2980327 ],
       [0.46100944],
       [0.82054225],
       [0.68978868],
       [0.3882674 ]])

Після застосування функції expand_dims з аргументом axis=1 ми додали розмірність нашому вектору, при цьому змінивши його орієнтацію з горизонатльної на вертикальну. Тепер він має розмірність (10, 1).





In [14]:
column_vector.T

array([[0.50863653, 0.55254229, 0.18093487, 0.19696164, 0.24708983,
        0.2980327 , 0.46100944, 0.82054225, 0.68978868, 0.3882674 ]])

Після транспонування наш вектор має розмірність (1, 10)